# Generated by Django 3.0.9 on 2020-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
                ('date', models.DateTimeField(blank=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
