# Generated by Django 3.0.9 on 2020-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faql',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
