# Generated by Django 3.0.9 on 2020-09-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=255)),
                ('DisplayName', models.CharField(blank=True, default='testing', max_length=256, null=True)),
                ('Weight', models.CharField(max_length=5)),
                ('Dimensions', models.CharField(max_length=20)),
                ('ScreenSize', models.CharField(max_length=4)),
                ('ScreenResolution', models.CharField(max_length=10)),
                ('MaxResolution', models.CharField(max_length=10)),
                ('DisplayType', models.BooleanField(default=True)),
                ('Color', models.CharField(max_length=10)),
                ('Speaker', models.CharField(blank=True, max_length=30)),
                ('PortsUsb2', models.CharField(max_length=2)),
                ('PortsUsb3', models.CharField(max_length=2)),
                ('PortsHdmi', models.CharField(max_length=2)),
                ('PortsAudio', models.CharField(max_length=2)),
                ('PortsEthernet', models.CharField(max_length=2)),
                ('PortsMicrophone', models.CharField(max_length=2)),
                ('PortsVga', models.CharField(max_length=2)),
                ('Ram', models.CharField(max_length=6)),
                ('RamTechnology', models.CharField(max_length=8)),
                ('HardDrive', models.CharField(blank=True, default='512', max_length=10)),
                ('HardDriveType', models.CharField(default=None, max_length=12)),
                ('Battery', models.CharField(max_length=15)),
                ('Os', models.CharField(max_length=20)),
                ('ProcessorName', models.CharField(max_length=5)),
                ('ProcessorSpeed', models.CharField(max_length=8)),
                ('ProcessorType', models.CharField(max_length=20)),
                ('Graphics', models.CharField(max_length=25)),
                ('IncludedComponents', models.TextField()),
                ('SoftwareIncluded', models.TextField()),
                ('DataLinkProtocol', models.CharField(default='IEEE 802.11 a/b/g/n/ac', max_length=20)),
                ('Company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laptop.Company')),
            ],
        ),
    ]
