# Generated by Django 3.0.9 on 2020-09-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ManyToManyField(related_name='business', to='Laptop.LaptopSpec')),
                ('gaming', models.ManyToManyField(related_name='gaming', to='Laptop.LaptopSpec')),
                ('student', models.ManyToManyField(related_name='student', to='Laptop.LaptopSpec')),
            ],
        ),
    ]
