# Generated by Django 3.0.9 on 2020-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='Image',
            field=models.ImageField(blank=True, upload_to='LapImages/'),
        ),
    ]
