# Generated by Django 3.0.9 on 2020-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0003_auto_20200822_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='HardDrive',
            field=models.CharField(default='512', max_length=10),
        ),
    ]
