# Generated by Django 3.0.9 on 2020-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0003_laptopspec_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='url',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
