# Generated by Django 3.0.9 on 2020-09-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0004_laptopspec_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='FullName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='laptopspec',
            name='DisplayName',
            field=models.CharField(blank=True, default='testing', max_length=128, null=True),
        ),
    ]
