# Generated by Django 3.0.9 on 2020-08-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0004_auto_20200823_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
