# Generated by Django 3.0.9 on 2020-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0005_auto_20200908_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='Company',
            field=models.CharField(max_length=32),
        ),
    ]
