# Generated by Django 3.0.9 on 2020-08-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='laptopspec',
            name='url',
            field=models.CharField(default='https://pornhub.com', max_length=40),
        ),
    ]
