# Generated by Django 3.0.9 on 2020-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0006_auto_20200825_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
