# Generated by Django 3.0.9 on 2020-08-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0007_auto_20200825_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopspec',
            name='url',
        ),
    ]
