# Generated by Django 3.0.9 on 2020-08-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0008_remove_laptopspec_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopspec',
            name='Image',
            field=models.ImageField(blank=True, upload_to='LapImages/'),
        ),
    ]
