# Generated by Django 3.0.9 on 2020-08-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0009_laptopspec_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopspec',
            name='HardDrive',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
