# Generated by Django 3.0.9 on 2020-08-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0011_auto_20200830_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopspec',
            name='Image',
        ),
    ]
