# Generated by Django 3.0.9 on 2020-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0012_laptopspec_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='counter',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
