# Generated by Django 3.0.9 on 2020-08-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0012_remove_laptopspec_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopspec',
            name='HardDrive',
        ),
    ]
