# Generated by Django 3.0.9 on 2020-08-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laptop', '0014_laptopspec_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopspec',
            name='Image',
        ),
    ]
